# Generated by Django 5.0.6 on 2024-05-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cofferApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DtatEntry",
            new_name="DataEntry",
        ),
    ]
